from __future__ import annotations

from pathlib import Path

import pytest

from makeyourbrick.io.ldr_writer import (
    brick_to_ldr_line,
    brick_to_ldraw_matrix,
    brick_to_ldraw_position,
    format_ldraw_number,
    write_ldr,
)
from makeyourbrick.types import Brick


def test_brick_to_ldraw_position_uses_ldraw_units() -> None:
    brick = Brick("3005.dat", color_id=16, x=2, y=3, z=4, width=1, depth=1)

    assert brick_to_ldraw_position(brick) == (40, -72, 80)


def test_brick_to_ldraw_position_uses_part_center_origin() -> None:
    assert brick_to_ldraw_position(Brick("3003.dat", 16, 0, 0, 0, 2, 2)) == (10, 0, 10)
    assert brick_to_ldraw_position(Brick("3001.dat", 16, 0, 0, 0, 2, 4)) == (10, 0, 30)
    assert brick_to_ldraw_position(Brick("3001.dat", 16, 0, 0, 0, 4, 2, rotation_degrees=90)) == (
        30,
        0,
        10,
    )


def test_format_ldraw_number_keeps_integer_output_compact() -> None:
    assert format_ldraw_number(10.0) == "10"
    assert format_ldraw_number(0.5) == "0.5"


def test_brick_to_ldr_line_writes_type_1_part_reference() -> None:
    brick = Brick("3005.dat", color_id=14, x=1, y=2, z=3, width=1, depth=1)

    line = brick_to_ldr_line(brick)
    tokens = line.split()

    assert line == "1 14 20 -48 60 1 0 0 0 1 0 0 0 1 3005.dat"
    assert len(tokens) == 15
    assert tokens[0] == "1"
    assert tokens[-1] == "3005.dat"


def test_brick_to_ldraw_matrix_supports_right_angle_rotations() -> None:
    assert brick_to_ldraw_matrix(Brick("3001.dat", 16, 0, 0, 0, 2, 4, rotation_degrees=0)) == (
        "1 0 0 0 1 0 0 0 1"
    )
    assert brick_to_ldraw_matrix(Brick("3001.dat", 16, 0, 0, 0, 4, 2, rotation_degrees=90)) == (
        "0 0 1 0 1 0 -1 0 0"
    )


def test_brick_to_ldraw_matrix_rejects_unsupported_rotation() -> None:
    brick = Brick("3001.dat", 16, 0, 0, 0, 2, 4, rotation_degrees=45)

    with pytest.raises(ValueError, match="Unsupported"):
        brick_to_ldraw_matrix(brick)


def test_write_ldr_includes_header_and_all_bricks() -> None:
    output_path = Path("outputs/ldr/test_writer_sample.ldr")
    bricks = [
        Brick("3005.dat", color_id=16, x=0, y=0, z=0, width=1, depth=1),
        Brick("3005.dat", color_id=4, x=1, y=0, z=0, width=1, depth=1),
    ]

    try:
        write_ldr(bricks, output_path, title="Sample")

        lines = output_path.read_text(encoding="utf-8").splitlines()
        assert lines[:3] == [
            "0 Sample",
            "0 Generated by MakeYourBrick",
            "0 Name: test_writer_sample.ldr",
        ]
        assert len([line for line in lines if line.startswith("1 ")]) == 2
    finally:
        output_path.unlink(missing_ok=True)


def test_write_ldr_can_insert_steps_between_layers() -> None:
    output_path = Path("outputs/ldr/test_writer_steps.ldr")
    bricks = [
        Brick("3005.dat", color_id=16, x=0, y=0, z=0, width=1, depth=1),
        Brick("3005.dat", color_id=16, x=1, y=0, z=0, width=1, depth=1),
        Brick("3005.dat", color_id=16, x=0, y=1, z=0, width=1, depth=1),
        Brick("3005.dat", color_id=16, x=0, y=2, z=0, width=1, depth=1),
    ]

    try:
        write_ldr(bricks, output_path, title="Layered", step_by_layer=True)

        lines = output_path.read_text(encoding="utf-8").splitlines()
        assert lines.count("0 STEP") == 2
        assert lines.index("0 STEP") > 3
    finally:
        output_path.unlink(missing_ok=True)


def test_write_ldr_omits_layer_steps_by_default() -> None:
    output_path = Path("outputs/ldr/test_writer_no_steps.ldr")
    bricks = [
        Brick("3005.dat", color_id=16, x=0, y=0, z=0, width=1, depth=1),
        Brick("3005.dat", color_id=16, x=0, y=1, z=0, width=1, depth=1),
    ]

    try:
        write_ldr(bricks, output_path)

        assert "0 STEP" not in output_path.read_text(encoding="utf-8")
    finally:
        output_path.unlink(missing_ok=True)
