from __future__ import annotations

from pathlib import Path

from makeyourbrick.types import Brick

STUD_LDU = 20
BRICK_HEIGHT_LDU = 24


def brick_to_ldr_line(brick: Brick) -> str:
    x = brick.x * STUD_LDU
    y = -brick.y * BRICK_HEIGHT_LDU
    z = brick.z * STUD_LDU
    matrix = "1 0 0 0 1 0 0 0 1"
    return f"1 {brick.color_id} {x} {y} {z} {matrix} {brick.part_id}"


def write_ldr(bricks: list[Brick], output_path: Path, title: str = "MakeYourBrick output") -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        f"0 {title}",
        "0 Generated by MakeYourBrick",
        "0 Name: lego_output.ldr",
    ]
    lines.extend(brick_to_ldr_line(brick) for brick in bricks)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return output_path

