from __future__ import annotations

from pathlib import Path

from makeyourbrick.types import Brick

STUD_LDU = 20
BRICK_HEIGHT_LDU = 24


def format_ldraw_number(value: float) -> str:
    if value == int(value):
        return str(int(value))
    return f"{value:.6f}".rstrip("0").rstrip(".")


def brick_to_ldraw_position(brick: Brick) -> tuple[float, float, float]:
    x = (brick.x + (brick.width - 1) / 2) * STUD_LDU
    y = -brick.y * BRICK_HEIGHT_LDU
    z = (brick.z + (brick.depth - 1) / 2) * STUD_LDU
    return x, y, z


def brick_to_ldraw_matrix(brick: Brick) -> str:
    rotation = brick.rotation_degrees % 360
    if rotation == 0:
        return "1 0 0 0 1 0 0 0 1"
    if rotation == 90:
        return "0 0 1 0 1 0 -1 0 0"
    if rotation == 180:
        return "-1 0 0 0 1 0 0 0 -1"
    if rotation == 270:
        return "0 0 -1 0 1 0 1 0 0"
    raise ValueError(f"Unsupported brick rotation: {brick.rotation_degrees}")


def brick_to_ldr_line(brick: Brick) -> str:
    x, y, z = brick_to_ldraw_position(brick)
    matrix = brick_to_ldraw_matrix(brick)
    position = " ".join(format_ldraw_number(value) for value in (x, y, z))
    return f"1 {brick.color_id} {position} {matrix} {brick.part_id}"


def write_ldr(
    bricks: list[Brick],
    output_path: Path,
    title: str = "MakeYourBrick output",
    step_by_layer: bool = False,
) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        f"0 {title}",
        "0 Generated by MakeYourBrick",
        f"0 Name: {output_path.name}",
    ]
    previous_layer: int | None = None
    for brick in bricks:
        if step_by_layer and previous_layer is not None and brick.y != previous_layer:
            lines.append("0 STEP")
        lines.append(brick_to_ldr_line(brick))
        previous_layer = brick.y
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return output_path
